In [ ]:
from google.colab import drive
drive.mount( "/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
e = d.drop(columns = ["high","low"])
e

        fund_symbol  price_date   open  close  adj_close  volume
0               AAA  2020-09-09  25.10  25.07      24.85   17300
1               AAA  2020-09-10  25.06  25.07      24.85   23500
2               AAA  2020-09-11  25.04  25.03      24.81   33400
3               AAA  2020-09-14  25.01  25.02      24.80   13100
4               AAA  2020-09-15  25.02  25.01      24.79   12100
...             ...         ...    ...    ...        ...     ...
3866025         ZSL  2021-11-23  26.81  26.35      26.35  190900
3866026         ZSL  2021-11-24  26.79  26.69      26.69  109000
3866027         ZSL  2021-11-26  26.67  27.72      27.72  205500
3866028         ZSL  2021-11-29  27.89  28.27      28.27  411900
3866029         ZSL  2021-11-30  28.15  28.49      28.49  219400

[3866030 rows x 6 columns]

In [ ]:
d = pd.read_csv("/content/drive/MyDrive/colab programaciÃ³n /ETF prices.csv")
d

        fund_symbol  price_date   open   high    low  close  adj_close  volume
0               AAA  2020-09-09  25.10  25.12  25.07  25.07      24.85   17300
1               AAA  2020-09-10  25.06  25.07  25.05  25.07      24.85   23500
2               AAA  2020-09-11  25.04  25.05  25.02  25.03      24.81   33400
3               AAA  2020-09-14  25.01  25.06  25.01  25.02      24.80   13100
4               AAA  2020-09-15  25.02  25.03  25.01  25.01      24.79   12100
...             ...         ...    ...    ...    ...    ...        ...     ...
3866025         ZSL  2021-11-23  26.81  27.21  26.30  26.35      26.35  190900
3866026         ZSL  2021-11-24  26.79  26.96  26.57  26.69      26.69  109000
3866027         ZSL  2021-11-26  26.67  28.14  26.67  27.72      27.72  205500
3866028         ZSL  2021-11-29  27.89  28.56  27.80  28.27      28.27  411900
3866029         ZSL  2021-11-30  28.15  28.73  25.91  28.49      28.49  219400

[3866030 rows x 8 columns]

In [ ]:
d.drop(columns=['high', 'low'])

        fund_symbol  price_date   open  close  adj_close  volume
0               AAA  2020-09-09  25.10  25.07      24.85   17300
1               AAA  2020-09-10  25.06  25.07      24.85   23500
2               AAA  2020-09-11  25.04  25.03      24.81   33400
3               AAA  2020-09-14  25.01  25.02      24.80   13100
4               AAA  2020-09-15  25.02  25.01      24.79   12100
...             ...         ...    ...    ...        ...     ...
3866025         ZSL  2021-11-23  26.81  26.35      26.35  190900
3866026         ZSL  2021-11-24  26.79  26.69      26.69  109000
3866027         ZSL  2021-11-26  26.67  27.72      27.72  205500
3866028         ZSL  2021-11-29  27.89  28.27      28.27  411900
3866029         ZSL  2021-11-30  28.15  28.49      28.49  219400

[3866030 rows x 6 columns]

In [ ]:
# selecciÃ³n por indises
d.iloc[0:100]

   fund_symbol  price_date   open   high    low  close  adj_close  volume
0          AAA  2020-09-09  25.10  25.12  25.07  25.07      24.85   17300
1          AAA  2020-09-10  25.06  25.07  25.05  25.07      24.85   23500
2          AAA  2020-09-11  25.04  25.05  25.02  25.03      24.81   33400
3          AAA  2020-09-14  25.01  25.06  25.01  25.02      24.80   13100
4          AAA  2020-09-15  25.02  25.03  25.01  25.01      24.79   12100
..         ...         ...    ...    ...    ...    ...        ...     ...
95         AAA  2021-01-26  25.16  25.17  25.16  25.17      25.02     500
96         AAA  2021-01-27  25.14  25.15  25.14  25.15      25.01     500
97         AAA  2021-01-28  25.15  25.15  25.15  25.15      25.01     200
98         AAA  2021-01-29  25.16  25.16  25.15  25.15      25.00    3100
99         AAA  2021-02-01  25.14  25.14  25.13  25.13      25.01    1300

[100 rows x 8 columns]

In [ ]:
e.mean(axis = 1)

<ipython-input-21-5bb99e2d2145>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  e.mean(axis = 1)

0            4343.7550
1            5893.7450
2            8368.7200
3            3293.7075
4            3043.7050
              ...
3866025     47744.8775
3866026     27270.0425
3866027     51395.5275
3866028    102996.1075
3866029     54871.2825
Length: 3866030, dtype: float64

In [ ]:
d.iloc[:, [1,2,5]]

         price_date   open  close
0        2020-09-09  25.10  25.07
1        2020-09-10  25.06  25.07
2        2020-09-11  25.04  25.03
3        2020-09-14  25.01  25.02
4        2020-09-15  25.02  25.01
...             ...    ...    ...
3866025  2021-11-23  26.81  26.35
3866026  2021-11-24  26.79  26.69
3866027  2021-11-26  26.67  27.72
3866028  2021-11-29  27.89  28.27
3866029  2021-11-30  28.15  28.49

[3866030 rows x 3 columns]

In [ ]:
d['low'].value_counts()

25.00       3415
25.10       2627
26.00       2608
25.50       2531
25.25       2465
            ...
18725.00       1
18906.25       1
898.24         1
896.32         1
204.06         1
Name: low, Length: 73939, dtype: int64

In [ ]:
d.shape

(3866030, 8)

In [ ]:
d.ndim

2

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

precios = np.random.rand(10)

precios

closed = np.random.randint(1, 100, 10)

In [ ]:
closed

array([79, 22, 13, 26, 74, 68, 29, 97,  2, 56])

In [ ]:
diccionario = ("Precios" : precios,
               "Cierre": closed)

import pandas as pd

precio = pd.DataFrame(diccionario)
precio

SyntaxError: ignored

In [ ]:
precio[precio['Cierre']>20]

NameError: ignored